### ISSUE TITLE
不支持双击

### ISSUE THREAD

**Issue by tonglei100** [tonglei100/sweetest#1]
不支持双击操作

**Comment by bulletforyou** [comment]
想问下支持千万级别的规模 如何保证性能的

**Comment by tonglei100** [comment]
@godfreyy 文档中说的千、万级别的规模，有3个方面：
1. 本框架用例类似于手工用例，更易于编写、维护和查阅，即使达到上万的用例也一目了然。
2. 如果是脚本用例，上万个用例的代码可能达到几十万行，难以维护。而本框架代码仅上千行，经过多个项目考验，运行稳定。
3. 执行层面，一般采用 TFS 或 jenkins，按项目配置代理机运行，一般建议100个用例以内做为一个执行任务，时间在一个小时以内，在接收范围之内。如果有1万个用例，那需要100小时，5台代理机，一天也可以执行完成了。
