### ISSUE TITLE
不支持mac上传文件

### ISSUE THREAD

**Issue by Tom-Deng** [tonglei100/sweetest#11]
web测试中文件上传是基于window下的python包pypiwin32实现的，有实现mac文件上传的计划吗？

**Comment by Tom-Deng** [comment]
通用页面下也没有文件的具体元素，可以提供一下吗，或者提供一个具体的文件上传demo

**Comment by tonglei100** [comment]
Mac 上我没找到支持的库，一般上传文件是可以通过send_keys(即 Sweetest中的：输入)来上传的
参考：https://zhuanlan.zhihu.com/p/31300170

如果不是`<input type="file" name="file"/>`格式，可能就不好办了
