### ISSUE TITLE
div滚动条没有自动滚到元素可见位置

### ISSUE THREAD

**Issue by xuss417** [tonglei100/sweetest#17]
元素需要div滚动条时可见，没有自动判断该滚动条滚动到元素可见位置

**Comment by xuss417** [comment]
解决办法：
1.在web.py文件在添加一个滚动条方法，ivu-drawer-body是div class的名称，可以写在元素中，也可以直接在方法中写死，建议写在元素excel中去获取
![image](https://user-images.githubusercontent.com/32625377/57512453-42f48b00-733e-11e9-87ed-0cade2d9dc83.png)
2.config文件中，添加对应的方法；
 '滚动条':'SCROLLBAR',
 'SCROLLBAR':'SCROLLBAR',
3.用例中直接添加使用 
![image](https://user-images.githubusercontent.com/32625377/57512637-c57d4a80-733e-11e9-977f-e917b781cc4b.png)

**Comment by tonglei100** [comment]
已添加滚动条关键字
