### ISSUE TITLE
压缩包不见了

### ISSUE THREAD

**Issue by wuqiunan** [tonglei100/sweetest#2]
<img width="1054" alt="wx20180728-175529 2x" src="https://user-images.githubusercontent.com/20646220/43355501-dd6d1084-928f-11e8-95a0-f12e9dc11fa9.png">

**Comment by tonglei100** [comment]
Mac 或 Linux 上，会有这种问题，请直接在 https://github.com/tonglei100/sweetest/tree/master/example 目录下载，解压
