### ISSUE TITLE
对于接口测试中涉及到上传功能，增加了优化，优化了testcase中的书写方式，看下是否可行？

### ISSUE THREAD

**Issue by killuayang90s** [tonglei100/sweetest#21]
在 `keywords / http.py`文件中增加：
增加了关键字`form` 用于POST方法 multipart/form-data提交数据方式的上传接口，在testcase中测试数据字段可书写为：
 - `form={r'./files/test.xls': 'application/vnd.ms-excel'}`
 - `form={r'./files/test.zip': 'application/zip}`

```python
    elif kw == 'post':
        if 'form' in data:
            form_dict = json2dict(data['form'])
            try:
                if len(form_dict) == 1:
                    for form_k, form_v in form_dict.items():
                        form_name = form_k.split("/")[-1]
                        form_data = MultipartEncoder(fields={'file': (form_name, open(form_k, 'rb'), form_v)})
                        form_headers = {'Content-Type': form_data.content_type}
                        http.r.headers.update(form_headers)
                        r = getattr(http.r, kw)(http.baseurl + url, data=form_data, timeout=timeout)
            except:
                logger.exception("***form can be only one Key-value***")
        else:
            r = getattr(http.r, kw)(http.baseurl + url,
                                    data=_data['data'], json=_data['json'], files=_data['files'], timeout=timeout, **data)
        logger.info(f'BODY: {r.request.body}')

```

增加了关键字`binary` 用于PUT方法二进制流的提交方式上传接口，在testcase中测试数据字段可书写为：
- `binary={r'./data/2209.jpg':'image/jpeg'}`

```python
    elif kw in ('put', 'patch'):
        if 'binary' in data:
            binary_dict = json2dict(data['binary'])
            try:
                if len(binary_dict) == 1:
                    for binary_k, binary_v in binary_dict.items():
                        binary_headers = {'Content-Type': binary_v}
                        http.r.headers.update(binary_headers)
                        with open(binary_k, 'rb') as binary_f:
                            r = getattr(http.r, kw)(http.baseurl + url, data=binary_f, timeout=timeout)
            except:
                logger.exception("*** binary can be only one Key-value***")
        else:
            r = getattr(http.r, kw)(http.baseurl + url,
                                    data=_data['data'], timeout=timeout, **data)
        logger.info(f'BODY: {r.request.body}')

    elif kw in ('delete', 'options'):
```

**Comment by tonglei100** [comment]
1. 上传文件一般只要在用例的测试数据字段中写：
files={'file': open(r'./files/test.xls', 'rb')'}  
请参考 requests 官方文档的写法：https://cn.python-requests.org/zh_CN/latest/user/quickstart.html#post

先看看上面的写法能不能解决你的问题

2. 如果你想更新 headers 中的 Content-Type，可以直接在测试数据中写：headers={'Content-Type': ‘image/jpeg’}
这里，你可以按如下写法试试
data={'file': open(r'./data/2209.jpg', 'rb')}

期待你的反馈

**Comment by killuayang90s** [comment]
感谢您的回答，我尝试了您建议方式，第一个问题是可以解决的，第二个问题仍然没解决。具体情况如下

1.对于POST方法 multipart/form-data提交数据方式的上传接口，用例的测试数据字段中写：
`files={'file': open(r'./files/test.xls', 'rb')'},,headers={'Content-Type':''},,`
其中`headers={'Content-Type':''}`为必须填写的，如果不填就无法正常上传。

2.PUT方法二进制流的提交方式上传接口，我使用了您建议的方法，但是仍然无法正常上传。
在测试用例数据中书写：`data={'file': open(r'./data/2209.jpg', 'rb')},,headers={'Content-Type':'image/jpeg'},,`
以这种方式上传到服务器的图片，无法正常显示。查看测试用例执行日志如下：
![Image_20200713140953](https://user-images.githubusercontent.com/49148415/87276543-212eff00-c513-11ea-9031-5b4f05de408d.png)

如果是在测试用例数据中书写：`binary={r'./data/2209.jpg':'image/jpeg'},,`
以这种方式上传到服务器的图片，能正常显示，测试用例执行日志如下：
![02](https://user-images.githubusercontent.com/49148415/87276576-2ee48480-c513-11ea-9df2-14fe2a657698.png)

看到2种方式在传输时BODY是存在差异的，但是具体的原因目前我还没搞清楚。

**Comment by tonglei100** [comment]
按你的 binary 的写法，你试试
data= open(r'./data/2209.jpg', 'rb'),, headers={'Content-Type':'image/jpeg'}

应该效果是一样的

**Comment by killuayang90s** [comment]
我试了你这种法式，确实是可以的。
感谢！
