### ISSUE TITLE
如果要自定义拓展click_and_hold等等底层方法应该怎么操作

### ISSUE THREAD

**Issue by milkmeowo** [tonglei100/sweetest#22]
https://github.com/tonglei100/sweetest/blob/master/sweetest/sweetest/keywords/web.py#L171

看到封装了很多方法，但如果想拓展这些方法，lib文件夹的自定义函数可以支持么？

如果要支持click_and_hold和release应该要怎么操作

**Comment by milkmeowo** [comment]
引申问题，如何拓展keywords

**Comment by tonglei100** [comment]
lib 里做不到，需要在 config.py 添加关键字，在web.py 里添加关键字函数
