### ISSUE TITLE
是否支持导入自定义模块？

### ISSUE THREAD

**Issue by leeyin** [tonglei100/sweetest#7]
注册时，手机号码是唯一的，自己写了一个生成未注册手机号码的方法，写注册功能的用例时，能否直接调用这个生成手机号码的方法，将其生成的手机号码做为测试输入数据？

**Comment by tonglei100** [comment]
可以的，不过这个是比较高级的功能，我一时没时间来写怎么做，建议直接生成测试数据来使用
